/**:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.02
    scale_linear_turbo:
      x: 0.0262

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 0.65

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button